robot:
    urdf: "/home/mahesh/catkin_ws/src/iai_robots/iai_donbot_description/robots/donbot2.urdf"
    joints_groups:
      ur5_arm: &ur5_arm
        ['ur5_shoulder_pan_joint', 'ur5_shoulder_lift_joint', 'ur5_elbow_joint', 'ur5_wrist_1_joint', 'ur5_wrist_2_joint', 'ur5_wrist_3_joint', 'gripper_joint', 'gripper_base_gripper_left_joint']
      full_body: ['odom_x_joint', 'odom_y_joint', 'odom_z_joint', *ur5_arm]

    joint_configurations:

      below_shelf:
       odom_x_joint: 0.1
       odom_y_joint: 0.3
       odom_z_joint: 0.01
       ur5_shoulder_pan_joint: 1.9823357809267463
       ur5_shoulder_lift_joint: -2.4299975516996142
       ur5_elbow_joint: -1.9762726255540713
       ur5_wrist_1_joint: 0.8666279970481103
       ur5_wrist_2_joint: 1.5855963769735366
       ur5_wrist_3_joint: -1.5770985888989753
       gripper_joint: 0
       gripper_base_gripper_left_joint: 0

      above_shelf:
        odom_x_joint: 0.1
        odom_y_joint: 0.3
        odom_z_joint: 0.01
        ur5_shoulder_pan_joint: 1.9823357809267463
        ur5_shoulder_lift_joint: -1.8299975516996142
        ur5_elbow_joint: -1.9762726255540713
        ur5_wrist_1_joint: 0.8666279970481103
        ur5_wrist_2_joint: 1.5855963769735366
        ur5_wrist_3_joint: -1.5770985888989753
        gripper_joint: 0
        gripper_base_gripper_left_joint: 0

      below_shelf1:
       ur5_shoulder_pan_joint: 1.9823357809267463
       ur5_shoulder_lift_joint: -2.4299975516996142
       ur5_elbow_joint: -1.9762726255540713
       ur5_wrist_1_joint: 0.8666279970481103
       ur5_wrist_2_joint: 1.5855963769735366
       ur5_wrist_3_joint: -1.5770985888989753
       gripper_joint: 0
       gripper_base_gripper_left_joint: 0

      above_shelf1:
        ur5_shoulder_pan_joint: 1.9823357809267463
        ur5_shoulder_lift_joint: -1.8299975516996142
        ur5_elbow_joint: -1.9762726255540713
        ur5_wrist_1_joint: 0.8666279970481103
        ur5_wrist_2_joint: 1.5855963769735366
        ur5_wrist_3_joint: -1.5770985888989753
        gripper_joint: 0
        gripper_base_gripper_left_joint: 0






