#robot:
#  groups:
#    - name: "right_arm"
#      joints: ["joint1", "joint2", "joint3"]
#    - name: "left_arm"
#      joints: ["joint4", "joint5", "joint6", "join7"]
#    - name: "full_body"
#      sub_groups: ["right_arm", "left_arm"]
#    - name: "full_body1"
#      sub_groups: ["right_arm", "left_arm"]
#robot:
#  groups:
#    - name: "right_arm"
#      joints: &right_arm
#        - ["joint0", "joint1", "joint2"]
#    - name: "left_arm"
#      joints: &left_arm
#        - ["joint3", "joint4", "joint5", "joint6"]
#    - name: "right_arm1"
#      joints: &right_arm1
#        - ["joint01", "joint11", "joint12"]
#
#    - name: "left_arm1"
#      joints: &left_arm1
#        - ["joint31", "joint14", "joint51", "joint16"]
#    - name: "full_body"
#      joints: [*right_arm, *left_arm]
#    - name: "full_body1"
#      joints: [*right_arm1, *left_arm1]


robot:
    urdf: "/home/mahe/catkin_ws/src/iai_robots/iai_boxy_description/robots/boxy_description.urdf"
    config_params:
      samples: 5
      duration: 6
    joints_groups:
#      joints:
      right_arm: &right_arm
        ["right_arm_1_joint", "right_arm_2_joint", "right_arm_3_joint", "right_arm_4_joint", "right_arm_5_joint", "right_arm_6_joint", "right_arm_flange_joint"]
      left_arm: &left_arm
        ["left_arm_1_joint", "left_arm_2_joint", "left_arm_3_joint", "left_arm_4_joint", "left_arm_5_joint", "left_arm_6_joint", "left_arm_flange_joint"]
      arm: [*right_arm, *left_arm]
    joint_configurations:
      right_home:
        right_arm_1_joint: -2.055
        right_arm_2_joint: 0.944
        right_arm_3_joint: -1.591
        right_arm_4_joint: -1.922
        right_arm_5_joint: 1.572
        right_arm_6_joint: 1.574
        right_arm_flange_joint: 1.571
      left_home:
        left_arm_1_joint: -2.055
        left_arm_2_joint: 0.944
        left_arm_3_joint: -1.591
        left_arm_4_joint: -1.922
        left_arm_5_joint: 1.572
        left_arm_6_joint: 1.574
        left_arm_flange_joint: 1.571
      arm_home:
        right_arm_1_joint: -2.055
        right_arm_2_joint: 0.944
        right_arm_3_joint: -1.591
        right_arm_4_joint: -1.922
        right_arm_5_joint: 1.572
        right_arm_6_joint: 1.574
        right_arm_flange_joint: 1.571

        left_arm_1_joint: -2.055
        left_arm_2_joint: 0.944
        left_arm_3_joint: -1.591
        left_arm_4_joint: -1.922
        left_arm_5_joint: 1.572
        left_arm_6_joint: 1.574
        left_arm_flange_joint: 1.571
