robot:
  groups:
    - name: "right_arm"
      joints: &right_arm
        - ["joint0", "joint1", "joint2"]

    - name: "left_arm"
      joints: &left_arm
        - ["joint3", "joint4", "joint5", "joint6"]
    - name: "full_body"
      joints: [*right_arm, *left_arm]
